name: Convert Jupyter README

on:
  push:
    branches:
    - master

jobs:
  release:
    if: github.actor == 'andresrcorcho' && startsWith(github.event.head_commit.message, 'Update README')
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Install dependencies & Convert README.ipynb
      run: |
        jupyter nbconvert --ClearMetadataPreprocessor.enabled=True --ClearOutput.enabled=True --to markdown README.ipynb
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Convert README.ipynb to README.md" -a
    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.ACCESS_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
